import type { ProviderDefinition } from "../core/types.js";

export const providerCatalog: ProviderDefinition[] = [
  {
    id: "codex-cli",
    name: "OpenAI Codex CLI",
    command: "codex",
    transport: "cli",
    cost: "included",
    automation: "full",
    status: "ready",
    official: true,
    homepage: "https://developers.openai.com/codex/cli",
    notes: "Connexion officielle avec un compte ChatGPT compatible. Moteur principal recommandé.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: true, structuredOutput: true, offline: false },
  },
  {
    id: "mistral-vibe",
    name: "Mistral Vibe CLI",
    command: "vibe",
    transport: "cli",
    cost: "free-tier",
    automation: "full",
    status: "ready",
    official: true,
    homepage: "https://docs.mistral.ai/vibe/code/cli/install-setup",
    notes: "Plan Mistral, clé compatible ou modèles locaux. Bon candidat pour construction et audit.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: true, structuredOutput: true, offline: true },
  },
  {
    id: "claude-code",
    name: "Anthropic Claude Code",
    command: "claude",
    transport: "cli",
    cost: "paid",
    automation: "full",
    status: "ready",
    official: true,
    homepage: "https://docs.anthropic.com/en/docs/claude-code/getting-started",
    notes: "Utilisable avec Claude Pro/Max ou facturation Console. Excellent pour refactorisation et revue.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: true, structuredOutput: true, offline: false },
  },
  {
    id: "gemini-cli",
    name: "Google Gemini CLI",
    command: "gemini",
    transport: "cli",
    cost: "unknown",
    automation: "full",
    status: "conditional",
    official: true,
    homepage: "https://github.com/google-gemini/gemini-cli",
    notes: "Accès dépendant du type de compte, de la licence ou d'une clé. Les offres évoluent rapidement.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: true, structuredOutput: true, offline: false },
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    command: "gh",
    transport: "cli",
    cost: "free-tier",
    automation: "assisted",
    status: "planned",
    official: true,
    homepage: "https://docs.github.com/en/copilot",
    notes: "Copilot Free ou abonnement. L'intégration exacte dépend des commandes disponibles dans le compte.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: false, structuredOutput: false, offline: false },
  },
  {
    id: "qwen-code",
    name: "Qwen Code",
    command: "qwen",
    transport: "cli",
    cost: "low-cost",
    automation: "full",
    status: "planned",
    official: true,
    homepage: "https://github.com/QwenLM/qwen-code",
    notes: "CLI ouverte avec Coding Plan, fournisseurs tiers, endpoints compatibles ou modèle local.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: true, structuredOutput: true, offline: true },
  },
  {
    id: "opencode",
    name: "OpenCode",
    command: "opencode",
    transport: "cli",
    cost: "unknown",
    automation: "full",
    status: "planned",
    official: false,
    homepage: "https://opencode.ai",
    notes: "Coquille agentique open source et multi-fournisseurs. À intégrer comme pont générique.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: true, structuredOutput: true, offline: true },
  },
  {
    id: "aider",
    name: "Aider",
    command: "aider",
    transport: "cli",
    cost: "unknown",
    automation: "full",
    status: "planned",
    official: false,
    homepage: "https://aider.chat",
    notes: "Agent de code open source compatible avec de nombreux modèles et serveurs locaux.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: true, structuredOutput: false, offline: true },
  },
  {
    id: "goose",
    name: "Block Goose",
    command: "goose",
    transport: "cli",
    cost: "unknown",
    automation: "full",
    status: "planned",
    official: false,
    homepage: "https://block.github.io/goose/",
    notes: "Agent open source extensible. Peut servir d'adaptateur vers plusieurs modèles.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: true, structuredOutput: false, offline: true },
  },
  {
    id: "ollama",
    name: "Ollama local",
    command: "ollama",
    transport: "local",
    cost: "local",
    automation: "full",
    status: "planned",
    official: false,
    homepage: "https://ollama.com",
    notes: "Option locale sans coût par requête, limitée par la puissance de la machine ou d'un serveur personnel.",
    capabilities: { readRepository: false, writeFiles: false, runCommands: false, structuredOutput: true, offline: true },
  },
  {
    id: "deepseek-web",
    name: "DeepSeek Web assisté",
    transport: "web-assisted",
    cost: "free-tier",
    automation: "assisted",
    status: "planned",
    official: true,
    homepage: "https://chat.deepseek.com",
    notes: "Préparation du prompt, ouverture du profil navigateur et import manuel de la réponse. Aucun contournement de quota.",
    capabilities: { readRepository: false, writeFiles: false, runCommands: false, structuredOutput: false, offline: false },
  },
  {
    id: "mistral-web",
    name: "Mistral Le Chat assisté",
    transport: "web-assisted",
    cost: "free-tier",
    automation: "assisted",
    status: "planned",
    official: true,
    homepage: "https://chat.mistral.ai",
    notes: "Voie web officielle avec transmission contrôlée d'un paquet de contexte expurgé.",
    capabilities: { readRepository: false, writeFiles: false, runCommands: false, structuredOutput: false, offline: false },
  },
  {
    id: "generic-openai-compatible",
    name: "API compatible OpenAI plafonnée",
    transport: "api",
    cost: "low-cost",
    automation: "full",
    status: "planned",
    official: false,
    homepage: "",
    notes: "Secours pour Groq, OpenRouter, DeepSeek, Mistral, modèles auto-hébergés et autres endpoints compatibles. Désactivé par défaut.",
    capabilities: { readRepository: false, writeFiles: false, runCommands: false, structuredOutput: true, offline: false },
  },
];
