import type { ProviderDefinition } from "../core/types.js";

export const providerCatalog: ProviderDefinition[] = [
  {
    id: "codex-cli",
    name: "OpenAI Codex CLI",
    command: "codex",
    transport: "cli",
    cost: "included",
    automation: "full",
    status: "ready",
    official: true,
    homepage: "https://developers.openai.com/codex/cli",
    notes: "Connexion officielle avec un compte ChatGPT compatible. Adaptateur contrôlé disponible.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: true, structuredOutput: true, offline: false },
  },
  {
    id: "mistral-vibe",
    name: "Mistral Vibe CLI",
    command: "vibe",
    transport: "cli",
    cost: "low-cost",
    automation: "full",
    status: "ready",
    official: true,
    homepage: "https://github.com/mistralai/mistral-vibe",
    notes: "Mode programmatique officiel avec plafonds prix/tokens/tours. Adaptateur sans shell disponible.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: false, structuredOutput: true, offline: false },
  },
  {
    id: "claude-code",
    name: "Anthropic Claude Code",
    command: "claude",
    transport: "cli",
    cost: "paid",
    automation: "full",
    status: "planned",
    official: true,
    homepage: "https://docs.anthropic.com/en/docs/claude-code/getting-started",
    notes: "Utilisable avec abonnement ou facturation Console. Adaptateur à construire après benchmark.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: true, structuredOutput: true, offline: false },
  },
  {
    id: "gemini-cli",
    name: "Google Gemini CLI",
    command: "gemini",
    transport: "cli",
    cost: "unknown",
    automation: "full",
    status: "conditional",
    official: true,
    homepage: "https://github.com/google-gemini/gemini-cli",
    notes: "Accès dépendant du compte ou de la licence. Les offres évoluent rapidement.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: true, structuredOutput: true, offline: false },
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    command: "gh",
    transport: "cli",
    cost: "free-tier",
    automation: "assisted",
    status: "planned",
    official: true,
    homepage: "https://docs.github.com/en/copilot",
    notes: "Copilot Free ou abonnement. Intégration à confirmer selon les commandes du compte.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: false, structuredOutput: false, offline: false },
  },
  {
    id: "qwen-code",
    name: "Qwen Code",
    command: "qwen",
    transport: "cli",
    cost: "low-cost",
    automation: "full",
    status: "planned",
    official: true,
    homepage: "https://github.com/QwenLM/qwen-code",
    notes: "CLI ouverte avec Coding Plan, fournisseurs tiers ou endpoint compatible.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: true, structuredOutput: true, offline: false },
  },
  {
    id: "opencode",
    name: "OpenCode",
    command: "opencode",
    transport: "cli",
    cost: "unknown",
    automation: "full",
    status: "planned",
    official: false,
    homepage: "https://opencode.ai",
    notes: "Coquille agentique open source et multi-fournisseurs. Candidat pont générique.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: true, structuredOutput: true, offline: true },
  },
  {
    id: "aider",
    name: "Aider",
    command: "aider",
    transport: "cli",
    cost: "unknown",
    automation: "full",
    status: "planned",
    official: false,
    homepage: "https://aider.chat",
    notes: "Agent Git open source compatible avec de nombreux fournisseurs.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: true, structuredOutput: false, offline: true },
  },
  {
    id: "goose",
    name: "Block Goose",
    command: "goose",
    transport: "cli",
    cost: "unknown",
    automation: "full",
    status: "planned",
    official: false,
    homepage: "https://block.github.io/goose/",
    notes: "Agent open source extensible. À étudier comme backend optionnel.",
    capabilities: { readRepository: true, writeFiles: true, runCommands: true, structuredOutput: false, offline: true },
  },
  {
    id: "ollama",
    name: "Ollama local expérimental",
    command: "ollama",
    transport: "local",
    cost: "local",
    automation: "full",
    status: "experimental",
    official: false,
    homepage: "https://ollama.com",
    notes: "Laboratoire futur séparé. Aucun modèle local n'est requis ou installé sur le Pi dans le MVP.",
    capabilities: { readRepository: false, writeFiles: false, runCommands: false, structuredOutput: true, offline: true },
  },
  {
    id: "deepseek-web",
    name: "DeepSeek Web assisté",
    transport: "web-assisted",
    cost: "free-tier",
    automation: "assisted",
    status: "planned",
    official: true,
    homepage: "https://chat.deepseek.com",
    notes: "Préparation du prompt et import manuel. Aucun contournement de quota.",
    capabilities: { readRepository: false, writeFiles: false, runCommands: false, structuredOutput: false, offline: false },
  },
  {
    id: "mistral-web",
    name: "Mistral Le Chat assisté",
    transport: "web-assisted",
    cost: "free-tier",
    automation: "assisted",
    status: "planned",
    official: true,
    homepage: "https://chat.mistral.ai",
    notes: "Voie web officielle avec paquet de contexte expurgé et transfert manuel.",
    capabilities: { readRepository: false, writeFiles: false, runCommands: false, structuredOutput: false, offline: false },
  },
  {
    id: "generic-openai-compatible",
    name: "API compatible plafonnée",
    transport: "api",
    cost: "low-cost",
    automation: "full",
    status: "planned",
    official: false,
    homepage: "",
    notes: "Secours désactivé par défaut, soumis au budget explicite du projet.",
    capabilities: { readRepository: false, writeFiles: false, runCommands: false, structuredOutput: true, offline: false },
  },
];
