import type { LocalToolDefinition } from "../core/types.js";

export const localToolCatalog: LocalToolDefinition[] = [
  {
    id: "git",
    name: "Git",
    commandCandidates: ["git"],
    category: "vcs",
    status: "required",
    lightweight: true,
    notes: "Source de vérité, branches, tags, diffs et worktrees.",
  },
  {
    id: "ripgrep",
    name: "ripgrep",
    commandCandidates: ["rg"],
    category: "search",
    status: "recommended",
    lightweight: true,
    notes: "Recherche rapide dans le dépôt et sélection de fichiers candidats.",
  },
  {
    id: "jq",
    name: "jq",
    commandCandidates: ["jq"],
    category: "utility",
    status: "recommended",
    lightweight: true,
    notes: "Inspection et transformation des sorties JSON des agents.",
  },
  {
    id: "sqlite",
    name: "SQLite",
    commandCandidates: ["sqlite3"],
    category: "database",
    status: "recommended",
    lightweight: true,
    notes: "État local des missions, événements, scores et reprises.",
  },
  {
    id: "repomix",
    name: "Repomix",
    commandCandidates: ["repomix"],
    category: "context",
    status: "recommended",
    lightweight: true,
    notes: "Paquets de contexte, comptage de tokens, compression et scan de secrets.",
  },
  {
    id: "aider",
    name: "Aider",
    commandCandidates: ["aider"],
    category: "agent",
    status: "optional",
    lightweight: true,
    notes: "Agent Git multi-modèles avec repo map, lint et tests.",
  },
  {
    id: "mini-swe-agent",
    name: "mini-SWE-agent",
    commandCandidates: ["mini"],
    category: "agent",
    status: "optional",
    lightweight: true,
    notes: "Boucle d'agent minimale, historique linéaire et exécution bash.",
  },
  {
    id: "opencode",
    name: "OpenCode",
    commandCandidates: ["opencode"],
    category: "agent",
    status: "optional",
    lightweight: true,
    notes: "Agent open source multi-fournisseurs avec modes plan et build.",
  },
  {
    id: "ollama",
    name: "Ollama",
    commandCandidates: ["ollama"],
    category: "inference",
    status: "optional",
    lightweight: false,
    notes: "Serveur simple pour petits modèles locaux ARM64.",
  },
  {
    id: "llama-cpp",
    name: "llama.cpp",
    commandCandidates: ["llama", "llama-server", "llama-cli"],
    category: "inference",
    status: "optional",
    lightweight: false,
    notes: "Moteur GGUF local finement configurable et compatible ARM64.",
  },
  {
    id: "localai",
    name: "LocalAI",
    commandCandidates: ["local-ai", "localai"],
    category: "inference",
    status: "experimental",
    lightweight: false,
    notes: "Passerelle locale multi-backends compatible avec plusieurs API.",
  },
  {
    id: "bubblewrap",
    name: "bubblewrap",
    commandCandidates: ["bwrap"],
    category: "sandbox",
    status: "recommended",
    lightweight: true,
    notes: "Isolation légère des commandes sur Linux.",
  },
  {
    id: "podman",
    name: "Podman",
    commandCandidates: ["podman"],
    category: "sandbox",
    status: "optional",
    lightweight: false,
    notes: "Conteneurs sans démon pour les missions nécessitant une isolation forte.",
  },
  {
    id: "docker",
    name: "Docker",
    commandCandidates: ["docker"],
    category: "container",
    status: "optional",
    lightweight: false,
    notes: "Compatibilité avec les projets et sandboxes existants.",
  },
  {
    id: "restic",
    name: "Restic",
    commandCandidates: ["restic"],
    category: "backup",
    status: "recommended",
    lightweight: true,
    notes: "Sauvegardes chiffrées des états, décisions et dépôts critiques.",
  },
];
